### ISSUE TITLE
Trennung von static und template Dateien

### ISSUE THREAD

**Issue by M-a-x-G** [FHBrandenburg/MTDjango#5]

**Comment by PatteWi** [comment]
Kleiner Zwischenstand:
Aktuell sieht es so aus, als ob keine der Dateien, weder Template noch Static, aufgerufen werden können, sobald in den Settings DEBUG=False festgelegt ist.

**Comment by PatteWi** [comment]
Zu der Debug=False-Problematik:
Sobald der Debug-Modus deaktiviert wurde, stellt Django keine Staticfiles mehr bereit, was wohl Sicherheitsgründe hat. Genaueres kann [hier](http://stackoverflow.com/questions/31097333/why-is-serving-static-files-insecure) entnommen werden. In Livesystemen ist es dann anscheinend Aufgabe des Webservers, die Staticfiles anhand von Berechtigungen bereitzustellen. Um in trotzdem lokal die Dateien im Debug=False-Mode bereitzustellen, muss der Server mit "runserver --insecure" gestartet werden.
[In diesem Thread](http://askbot.org/en/question/7338/static-files-css-js-and-images-not-served/) gibt es weiterführende Infomationen, was z.B. an einem Apache konfiguriert werden müsste. Somit sollte die Notwendigkeit der Trennung der static und template-Dateien entfallen, da diese nur vorgenommen werden sollte, weil auf die Templates direkt zugegriffen werden konnte.
